development:
  sessions:
    default:
      database: chromessengerbackend_development
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      uri: <%= ENV['MONGO_URL'] %>
      options:
        max_retries: 1
        retry_interval: 0
  options:
    raise_not_found_error: false

